server:
  port: 8888

spring:
    application:
        name: microservice-consumer
    cloud:
      loadbalancer:
        ribbon:
          enabled: false
eureka:
  client:
    registerWithEureka: false
    fetchRegistry: true
    serviceUrl:
      defaultZone: http://eureka-host1:8097/eureka/,http://eureka-host2:8098/eureka/,http://eureka-host3:8099/eureka/
      